Vagrant.configure("2") do |config|
  config.vm.base_mac = nil
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
    vb.linked_clone = true
  end

  N = 3
  (1..N).each do |machine_id|
    config.vm.define "docker-#{machine_id}" do |n|
      n.vm.hostname = "docker-#{machine_id}"
      n.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"
      n.vm.box = "debian/buster64"

      if machine_id == N
        n.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "site.yaml"
          ansible.raw_arguments = [ "-D"]
        end
      end
    end
  end
end
