Vagrant.configure("2") do |config|
  config.vm.base_mac = nil

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.define "kali" do |n|
    n.vm.network "private_network", type: "dhcp", virtualbox_intnet: "NatNetwork"
    n.vm.box = "kalilinux/rolling"
  end

  config.vm.define "vulnbox" do |n|
    n.vm.network "private_network", type: "dhcp", virtualbox_intnet: "NatNetwork"
    n.vm.box = "rapid7/metasploitable3-ub1404"
  end
end
