Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "./vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["./vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.cpus = 1
  end

## HOW TO CONNECT VIA SSH to VM:
## ssh -i ~/.vagrant.d/insecure_private_key -p 2202 vagrant@127.0.0.1
## for windows use putty and private key insecure_private_key. path is simular to linux, except ~/ use C:/users/...

## HOW TO ENABLE NAT NETWORK
## comment n.vm.network "forwarded_port" ... on every vm in config below
## uncomment n.vm.network "private_network" .... on every vm in config below

  config.vm.define "admin" do |n|
    n.vm.network "forwarded_port", guest: 22, host: 2001
    n.vm.network "private_network", type: "dhcp", virtualbox__intnet: "NatNetwork"
    n.vm.box = "debian/buster64"
  end

  config.vm.define "node1" do |n|
    n.vm.network "forwarded_port", guest: 22, host: 2002 
    n.vm.network "private_network", type: "dhcp", virtualbox__intnet: "NatNetwork"
    n.vm.box = "debian/buster64"
  end

  config.vm.define "node2" do |n|
    n.vm.network "forwarded_port", guest: 22, host: 2003
    n.vm.network "private_network", type: "dhcp", virtualbox__intnet: "NatNetwork"
    n.vm.box = "debian/buster64"
  end

  config.vm.define "node3" do |n|
    n.vm.network "forwarded_port", guest: 22, host: 2004
    n.vm.network "private_network", type: "dhcp", virtualbox__intnet: "NatNetwork"
    n.vm.box = "centos/7"
  end
end
